baseURL = "https://aakanksha0620.github.io/brew-bits/"
languageCode = "en-us"
title = "Brew Bits: Coding, Caffeine & Curiosity"
theme = "PaperMod"

# IMPORTANT FOR GITHUB PAGES
relativeURLs = false
canonifyURLs = false
uglyURLs = false

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]

# PaperMod recommended config
[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = true
  UseHugoToc = true

  # Optional
  disableThemeToggle = false
  disableScrollToTop = false

# Menu
[menu]

  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

  [[menu.main]]
	name = "Java"
	url = "/posts/java/"
	weight = 2

  [[menu.main]]
	name = "DSA"
	url = "/posts/dsa/"
	weight = 3

  [[menu.main]]
	name = "GenAI"
	url = "/posts/genai/"
	weight = 4

# Syntax highlighting
[markup]

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true       # required for mermaid + HTML blocks

  [markup.highlight]
    noClasses = false     # required for PaperMod CSS
    codeFences = true
    guessSyntax = true
    style = "dracula"
    lineNos = true


